# Generated by Django 5.1.2 on 2024-11-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramiapp', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='prf_image',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdname', models.CharField(max_length=255)),
                ('nos', models.IntegerField()),
                ('pdprice', models.IntegerField()),
                ('pd_desc', models.CharField(max_length=255)),
                ('pdimage', models.ImageField(null=True, upload_to='image/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ceramiapp.category')),
            ],
        ),
    ]
