# Generated by Django 5.1.2 on 2024-11-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramiapp', '0003_alter_userdetails_prf_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdimage',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
    ]
