# Generated by Django 5.1.2 on 2024-11-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceramiapp', '0006_alter_cart_total_price_alter_product_pdprice_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
