# Generated by Django 5.1.2 on 2024-11-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceramiapp', '0007_rename_cart_id_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
