# Generated by Django 5.1.2 on 2024-11-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceramiapp', '0008_remove_order_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
