# Generated by Django 5.1.2 on 2024-11-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceramiapp', '0010_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
