# Generated by Django 5.1.2 on 2024-11-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramiapp', '0014_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
